# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: gcr.io/k8s-k3s-386221
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.7.0-7321a1b"
  pullPolicy: Always
  # Always, IfNotPresent, Never
secret:
  env: TELE_TOKEN
  key: token
  name: kbot
