name: Secret reset workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      target-env:
        type: environment
        description: Select the environment
        required: true
        default: demo1

jobs:
  secrets_reset:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.target-env }}
      url: https://t.me/kbot_386221_bot

    steps:
    
    # Runs a single command using the runners shell
    - name: Indicate Start
      run: echo "Resetting secrets for ${{ github.event.inputs.target-env }} environment"
    
    # - uses: actions/checkout@v1
    
    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: 'apiVersion: v1'
      with:
        args: |
          kubectl
          create secret kbot
          -n ${{ github.event.inputs.target-env }}
          --dry-run=client --validate=false -o yaml
          --from-literal=$TELE_TOKEN
          > secret.yaml
    
    - run: cat secret.yaml && rm secret.yaml
    
#     - run: |
#         git config user.name github-actions
#         git config user.email github-actions@github.com
#         git commit -am "update version $VERSION"
#         git push
    
#     - run: |
#        ;; kubectl -n ${{ github.event.inputs.target-env }} create secret kbot --dry-run -o yaml --from-literal=$TELE_TOKEN > secret.yaml
#        && cat secret.yaml
#        ;; rm secret.yaml
    
#     - run: |
#        ; curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
#        ; 
#        ; kubectl -n ${{ github.event.inputs.target-env }} create secret kbot --dry-run -o yaml --from-literal=$TELE_TOKEN > secret.yaml
#        ; cat secret.yaml
#        ; rm secret.yaml
#        ; wget https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64
       
