name: Secret reset workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      target-env:
        type: environment
        description: Select the environment
        required: true
        default: 'demo'

jobs:
  greet:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.target-env }}
      url: https://t.me/kbot_386221_bot

    steps:
    
    # Runs a single command using the runners shell
    - name: Indicate Start
      run: echo "Resetting secrets for ${{ github.event.inputs.target-env }} environment"
    
    - name: dfsg
    - uses: actions/checkout@v1
    - run: |
       ;; kubectl -n ${{ github.event.inputs.target-env }} create secret kbot --dry-run -o yaml --from-literal=$TELE_TOKEN > secret.yaml
       && cat secret.yaml
       ;; rm secret.yaml
    
#     - run: |
#        ; curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
#        ; 
#        ; kubectl -n ${{ github.event.inputs.target-env }} create secret kbot --dry-run -o yaml --from-literal=$TELE_TOKEN > secret.yaml
#        ; cat secret.yaml
#        ; rm secret.yaml
#        ; wget https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64
       
